// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.2
// source: health.proto

package health

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthReporter_Ping_FullMethodName = "/api.HealthReporter/Ping"
)

// HealthReporterClient is the client API for HealthReporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthReporterClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
}

type healthReporterClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthReporterClient(cc grpc.ClientConnInterface) HealthReporterClient {
	return &healthReporterClient{cc}
}

func (c *healthReporterClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResp)
	err := c.cc.Invoke(ctx, HealthReporter_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthReporterServer is the server API for HealthReporter service.
// All implementations must embed UnimplementedHealthReporterServer
// for forward compatibility.
type HealthReporterServer interface {
	Ping(context.Context, *PingReq) (*PingResp, error)
	mustEmbedUnimplementedHealthReporterServer()
}

// UnimplementedHealthReporterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthReporterServer struct{}

func (UnimplementedHealthReporterServer) Ping(context.Context, *PingReq) (*PingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedHealthReporterServer) mustEmbedUnimplementedHealthReporterServer() {}
func (UnimplementedHealthReporterServer) testEmbeddedByValue()                        {}

// UnsafeHealthReporterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthReporterServer will
// result in compilation errors.
type UnsafeHealthReporterServer interface {
	mustEmbedUnimplementedHealthReporterServer()
}

func RegisterHealthReporterServer(s grpc.ServiceRegistrar, srv HealthReporterServer) {
	// If the following call pancis, it indicates UnimplementedHealthReporterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthReporter_ServiceDesc, srv)
}

func _HealthReporter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthReporterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthReporter_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthReporterServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthReporter_ServiceDesc is the grpc.ServiceDesc for HealthReporter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthReporter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.HealthReporter",
	HandlerType: (*HealthReporterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _HealthReporter_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health.proto",
}
