// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: ext.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpProxyAccessRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	NoAuth        bool                   `protobuf:"varint,2,opt,name=no_auth,json=noAuth,proto3" json:"no_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpProxyAccessRule) Reset() {
	*x = HttpProxyAccessRule{}
	mi := &file_ext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpProxyAccessRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpProxyAccessRule) ProtoMessage() {}

func (x *HttpProxyAccessRule) ProtoReflect() protoreflect.Message {
	mi := &file_ext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpProxyAccessRule.ProtoReflect.Descriptor instead.
func (*HttpProxyAccessRule) Descriptor() ([]byte, []int) {
	return file_ext_proto_rawDescGZIP(), []int{0}
}

func (x *HttpProxyAccessRule) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpProxyAccessRule) GetNoAuth() bool {
	if x != nil {
		return x.NoAuth
	}
	return false
}

var file_ext_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpProxyAccessRule)(nil),
		Field:         66001,
		Name:          "ext.http_proxy_access_rule",
		Tag:           "bytes,66001,opt,name=http_proxy_access_rule",
		Filename:      "ext.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         66001,
		Name:          "ext.is_rpc_port",
		Tag:           "varint,66001,opt,name=is_rpc_port",
		Filename:      "ext.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional ext.HttpProxyAccessRule http_proxy_access_rule = 66001;
	E_HttpProxyAccessRule = &file_ext_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional bool is_rpc_port = 66001;
	E_IsRpcPort = &file_ext_proto_extTypes[1]
)

var File_ext_proto protoreflect.FileDescriptor

const file_ext_proto_rawDesc = "" +
	"\n" +
	"\text.proto\x12\x03ext\x1a google/protobuf/descriptor.proto\"F\n" +
	"\x13HttpProxyAccessRule\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x17\n" +
	"\ano_auth\x18\x02 \x01(\bR\x06noAuth:o\n" +
	"\x16http_proxy_access_rule\x12\x1e.google.protobuf.MethodOptions\x18у\x04 \x01(\v2\x18.ext.HttpProxyAccessRuleR\x13httpProxyAccessRule:>\n" +
	"\vis_rpc_port\x12\x1c.google.protobuf.EnumOptions\x18у\x04 \x01(\bR\tisRpcPortB.Z,github.com/995933447/microgosuit/skeleton/pbb\x06proto3"

var (
	file_ext_proto_rawDescOnce sync.Once
	file_ext_proto_rawDescData []byte
)

func file_ext_proto_rawDescGZIP() []byte {
	file_ext_proto_rawDescOnce.Do(func() {
		file_ext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ext_proto_rawDesc), len(file_ext_proto_rawDesc)))
	})
	return file_ext_proto_rawDescData
}

var file_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ext_proto_goTypes = []any{
	(*HttpProxyAccessRule)(nil),        // 0: ext.HttpProxyAccessRule
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
	(*descriptorpb.EnumOptions)(nil),   // 2: google.protobuf.EnumOptions
}
var file_ext_proto_depIdxs = []int32{
	1, // 0: ext.http_proxy_access_rule:extendee -> google.protobuf.MethodOptions
	2, // 1: ext.is_rpc_port:extendee -> google.protobuf.EnumOptions
	0, // 2: ext.http_proxy_access_rule:type_name -> ext.HttpProxyAccessRule
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ext_proto_init() }
func file_ext_proto_init() {
	if File_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ext_proto_rawDesc), len(file_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_ext_proto_goTypes,
		DependencyIndexes: file_ext_proto_depIdxs,
		MessageInfos:      file_ext_proto_msgTypes,
		ExtensionInfos:    file_ext_proto_extTypes,
	}.Build()
	File_ext_proto = out.File
	file_ext_proto_goTypes = nil
	file_ext_proto_depIdxs = nil
}
